### ISSUE TITLE
Not able to use the default login

### ISSUE THREAD

**Issue by hectorjoey** [ppazos/cabolabs-ehrserver#1059]
**Describe the bug**
I wanted to run the EHR server locally after then I couldn't log in

**Comment by ppazos** [comment]
@hectorjoey what is the login you tried?

**Comment by hectorjoey** [comment]
I have resolved the log in issue .. I found the credentials in the codebase.

**Comment by hectorjoey** [comment]
I cant create a user or account . or perform any create operation. what do i do? thank you

**Comment by hectorjoey** [comment]
also on the video on the login page, we have three fields which are username, password, and organization. while the one I have here just have a username and password; is that suppose to be a concern?
![ehr](https://user-images.githubusercontent.com/27903926/74945174-916ba580-53f7-11ea-89cf-17bbc4c30d58.PNG)

**Comment by ppazos** [comment]
thanks @hectorjoey the videos you saw are for 1.x, the version you are testing is 2.1alpha

**Comment by hectorjoey** [comment]
I cant create a user or account . or perform any create operation. what do i do? thank you

**Comment by ppazos** [comment]
@hectorjoey you are testing a non-stable version ("alpha" means not stable) that is under heavy development, fork branch 1.5 for testing.

**Comment by ppazos** [comment]
Closing since this is not a bug but related to usage questions.

**Comment by asdwtwty** [comment]
I also have the same question after the ehrserver installed. I wonder what is the default username(email) and password, or how could i created them. thanks

**Comment by nr23730** [comment]
To answer your question:

Email:
admin@cabolabs.com
Password: 
admin

I obtained the credentials from the source code.

**Comment by ppazos** [comment]
@asdwtwty @nr23730 it's documented in the guide https://cloudehrserver.com/learn
