### ISSUE TITLE
i cant delete an EHR after creating one

### ISSUE THREAD

**Issue by hectorjoey** [ppazos/cabolabs-ehrserver#1070]
Good afternoon, 
I am having an issue which is that I can't delete EHR after creating one. What can I do?
Thanks in advance

**Comment by ppazos** [comment]
Hi @hectorjoey deleting EHRs is not currently supported, since that would need a lot of validations in a production environment, and might depend on local regulations. 

For questions please use https://gitter.im/CaboLabs/EHRServer
