### ISSUE TITLE
Data display for composition - standardise?

### ISSUE THREAD

**Issue by samheard** [ppazos/cabolabs-ehrserver#113]
Ocean has some display scripts for encounters that I believe are on the openEHR site. There may be others. I would suggest that we should go with the XML for full display and use a standard display which leaves out non-helpful information (Tree, Item...) for the user.

I believe that the idea of a display broker will become necessary quite quickly but you will probably need a user, group, access implementation before it will be relevant.

**Comment by ppazos** [comment]
Thanks Sam, that will be a great addition. Current html composition display is very basic. Can you send me the link where I can find the standardized format?

**Comment by ppazos** [comment]
Integrate the XSLT from here: https://openehr.atlassian.net/wiki/display/dev/openEHR+Composition+XML+to+HTML

**Comment by ppazos** [comment]
XSLT in Groovy + Custom transformations http://www.pleus.net/blog/?p=1448

**Comment by ppazos** [comment]
We will use this XSLT: openEHR_RMtoHTML.xsl

**Comment by ppazos** [comment]
@samheard I have added the xslt, now the view of the clinical document looks better :cake:
