### ISSUE TITLE
Improve REST services URLs

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#13]
Right now, URLs are like these:

* /rest/ehrList
* /rest/ehrForSubject?subjectUid=xxx
* /rest/ehrGet?ehrUid=xxx
* /rest/patientList
* /rest/queryList
* /rest/queryShow?queryUid=xxx
* /rest/queryData?...
* /rest/queryCompositions?...

These URLs should be changed to something more simple and easy to remember, and to make space partitions of the entities we have based on the URL parts:

* /rest/ehrs -- list of all EHRs
* /rest/ehrs/ehrUid/xxx -- one EHR based on ehrUid partition
* /rest/ehrs/subjecUid/xxx -- one EHR based on the subjectUid partition
* /rest/patients -- list of all patients
* /rest/queries -- list of all queries
* /rest/queries/queryUid/xxx -- one query based on queryUid partition
* /rest/queries/queryUid/xxx/execute -- executes query xxx, each query knows its own type, this can be a queryData or a queryComposition

-- ideas for retrieveing queries (also for other entities to query by other pertitions and search criteria)
* /rest/queries/name/this.is.a.name -- list queries which name is equal to "this.is.a.name" (spaces transformed into ".")
* /rest/queries/descriptionContains/a.text.to.find -- list of queries that contains the "a.text.to.find" text ("description" partition with "contains" criteria)

**Comment by casiodbx** [comment]
Me pongo con ella @ppazos. Como ya hablamos, si tengo alguna duda ya te voy comentando.

**Comment by ppazos** [comment]
@casiodbx excelente!

**Comment by casiodbx** [comment]
Acabo de estar echando un vistazo de como está el codigo. Y por ejemplo:
   -Para  mostar lista de ehrs la url antigua sería /ehr/person/list y de la nueva forma /ehr/ehrs. Para hacerlo estoy modificando el UrlMapping.groovy.
 "/ehrs"( // por defecto va al escritorio del EHR Server
            controller: 'ehr',
            action: 'list'
        )
@ppazos Si no es así me lo dices y si es correcto sigo adelante con el resto. 
Un saludo.

**Comment by ppazos** [comment]
@casiodbx cuidado, esas son urls de las pantallas no de los servicios rest. Los servicios rest empiezan en rest/... esas son las unicas que hay que cambiar. Si quieres hablamos 5 minutos y te muestro las urls.

**Comment by casiodbx** [comment]
ok. No hay problema @ppazos . Entendido ya las tengo localizadas. Me pongo con ello. Si veo que me lio ya el lunes hablamos. Te parece?.

**Comment by ppazos** [comment]
perfecto, por las dudas, todas esas urls usan el controller "rest", por eso tienen /rest al principio de la url :D

**Comment by casiodbx** [comment]
@ppazos he estado mirando documentación y tengo algunas dudas de como hacerlo. Podriamos charlar el lunes a eso de las 20:00 horas en España(15:00 horas para tí).

**Comment by casiodbx** [comment]
@ppazos acabo de crear el pull request de esta tarea. Echale un vistazo y si ves algo mal me lo comentas. Espero que funcione correctamente. Cuando quieras me indicas la siguiente issue a realizar.

**Comment by ppazos** [comment]
El fin de semana lo testeo y hago el merge, gracias!

2015-09-15 13:17 GMT-03:00 Juan Carlos Álvarez Martín <
notifications@github.com>:

> @ppazos <https://github.com/ppazos> acabo de crear el pull request de
> esta tarea. Echale un vistazo y si ves algo mal me lo comentas. Espero que
> funcione correctamente. Cuando quieras me indicas la siguiente issue a
> realizar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ppazos/cabolabs-ehrserver/issues/13#issuecomment-140448756>
> .
>



-- 
Ing. Pablo Pazos Gutiérrez
Cel:(00598) 99 043 145
Skype: cabolabs
<http://cabolabs.com/>
http://www.cabolabs.com
pablo.pazos@cabolabs.com

**Comment by casiodbx** [comment]
ok @ppazos ya me diras como fue. Y lo dicho cuando puedas me dices y me pongo con otro issue. Saludos

**Comment by ppazos** [comment]
done
