### ISSUE TITLE
Error al mostrar los templates

### ISSUE THREAD

**Issue by casiodbx** [ppazos/cabolabs-ehrserver#138]
Cuando pulsamos en el menú la opción de Templates y nos los muestra el listado con todos. Si pulsamos sobre uno de la lista para que nos lo muestre da error.

**Comment by casiodbx** [comment]
@ppazos he resuelto este issue. Me podrias indicar los pasos para subir las solución:
1) ¿No se si antes me lo tengo que asignar, pero no se como?
2) Hago un commit -m "Nombre del issue resuelto" a mi repositorio local.
3) Ya desde gitHub hago un pull requests
pd: Para solucionarlo he creado la clousure show y muestro por pantalla el xml, no se si con eso es suficiente...

**Comment by ppazos** [comment]
Envía un pull request al repo de github para poder revisar el fix, gracias!

**Comment by ppazos** [comment]
done.
