### ISSUE TITLE
Agregar transformación canónica XML -> JSON para transformar XMLs de compositions

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#140]
Se utilizará como salida de las consultas de composition donde el output se solicite en formato JSON. La transformación debe ser genérica (no depender de nombres de elementos o atributos), y recorrer la estructura completa del XML de entrada.

Mapping rules:

    <data xsi:type="COMPOSITION" archetype_node_id="openEHR-EHR-COMPOSITION.signos.v1">
      <name>
        <value>Signos vitales</value>
      </name>
      <archetype_details>
        <archetype_id>
          <value>openEHR-EHR-COMPOSITION.signos.v1</value>
        </archetype_id>
        <template_id>
          <value>Signos</value>
        </template_id>
        <rm_version>1.0.2</rm_version>
      </archetype_details>
    ...

    {
      "data": {
        "@xsi:type": "COMPOSITION",
        "@archetype_node_id": "openEHR-EHR-COMPOSITION.signos.v1",
        "name": {
          "value": "Signos vitales"
        },
        "archetype_details": {
          "archetype_id": {
            "value": "openEHR-EHR-COMPOSITION.signos.v1"
          },
          "template_id": {
            "value": "Signos"
          },
          "rm_version": "1.0.2"
        },
    ...

**Comment by casiodbx** [comment]
Tengo una duda. Te refieres a que el resultado de una query tipo composition se pueda mostrar en formato JSON aparte de XML???. De momento por lo que he visto solo se muestran en XML..
Y a mayores esta opción se añadiria tanto cuando se crea una query como cuando se ejecuta(Y se pondría justo debajo de SoapUI?)

**Comment by ppazos** [comment]
La idea sería hacer un servicio que transforme una Version en XML a JSON. Sería uno de los archivos que se guardan en /versions.
Eso es independiente de las consultas. Luego, si para una consulta de compositions selecciona formato JSON, el proceso va a usar el servicio de conversión de XML a JSON.
Así que la transformación y la query son independientes.

**Comment by casiodbx** [comment]
Entendido. Gracias por la aclaración.

**Comment by casiodbx** [comment]
Ya tengo el issue casí terminado. Espero poder hacer mañana las últimas pruebas y subo el código.

**Comment by ppazos** [comment]
Si necesitas que pruebe algo, me avisas!

2015-08-04 15:45 GMT-03:00 Juan Carlos Álvarez Martín <
notifications@github.com>:

> Ya tengo el issue casí terminado. Espero poder hacer mañana las últimas
> pruebas y subo el código.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ppazos/cabolabs-ehrserver/issues/140#issuecomment-127709027>
> .
>



-- 
Ing. Pablo Pazos Gutiérrez
Cel:(00598) 99 043 145
Skype: cabolabs
<http://cabolabs.com/>
http://www.cabolabs.com
pablo.pazos@cabolabs.com

**Comment by ppazos** [comment]
Juan, estos ejemplos pueden ayudarte:

    <data xsi:type="COMPOSITION" archetype_node_id="openEHR-EHR-COMPOSITION.signos.v1">
      <name>
        <value>Signos vitales</value>
      </name>
      <archetype_details>
        <archetype_id>
          <value>openEHR-EHR-COMPOSITION.signos.v1</value>
        </archetype_id>
        <template_id>
          <value>Signos</value>
        </template_id>
        <rm_version>1.0.2</rm_version>
      </archetype_details>
      <language>
        <terminology_id>
          <value>ISO_639-1</value>
        </terminology_id>
        <code_string>es</code_string>
      </language>
      <territory>
        <terminology_id>
          <value>ISO_3166-1</value>
        </terminology_id>
        <code_string>UY</code_string>
      </territory>
      <category>
        ...
      </category>
      ...
    </data>

    {
      "data": {
        "@xsi:type": "COMPOSITION",
        "@archetype_node_id": "openEHR-EHR-COMPOSITION.signos.v1",
        "name": {
          "value": "Signos vitales"
        },
        "archetype_details": {
          "archetype_id": {
            "value": "openEHR-EHR-COMPOSITION.signos.v1"
          },
          "template_id": {
            "value": "Signos"
          },
          "rm_version": "1.0.2"
        },
        "language": {
          "terminology_id": {
            "value": "ISO_639-1"
          }
        },
        "territory": {
          "terminology_id": {
            "value": "ISO_3166-1"
          }
        },
        "category": {
          ...
        }
      }
    }

**Comment by ppazos** [comment]
Done thanks to @casiodbx
