### ISSUE TITLE
Fix paginator style on lists pages

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#156]
The default grails paginator doesn't look nice with the bootstrap theme, and the generated DOM doesn't matches the bootstrap paginator DOM.

1. Create a paginator taglib that generates bootstrap paginators
2. Add bootstrap style

**Comment by casiodbx** [comment]
@ppazos Mañana me pongo con ella. Como siempre si me surge alguna duda te pregunto.

**Comment by ppazos** [comment]
Merged PR.
