### ISSUE TITLE
Add info about building to README

### ISSUE THREAD

**Issue by andmos** [ppazos/cabolabs-ehrserver#191]
Hi! 

I would like to build and try out this openEhr-implementation, but I am having some trouble building the project... Is it possible to add a section to the README describing the build process? 
Thanks!

**Comment by ppazos** [comment]
@andmos BTW, we have a public staging env you can use: https://cabolabs-ehrserver.rhcloud.com/ehr-0.3/

Just consider that is under heavy development, stuff can break until the v0.4 release (very soon!)

**Comment by andmos** [comment]
Cool! Did not see the PDF (old README-habit i guess),  keep up the good work! Love to see openEhr development out in the open!

**Comment by ppazos** [comment]
@andmos No prob, the PDF is a little outdated but should work or at least help. When we release v0.4, I'll update the guide, readme and make a hangout demo (open so people can actually join and have a little Q/A). I'll notify through twitter, fb, g+, linkedin, etc.

**Comment by ppazos** [comment]
This is done. Plus, we have https://cloudehrserver.com/
