### ISSUE TITLE
Add versionedComposition list to the admin/orgman menu to audit versions

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#210]
http://localhost:8090/ehr/versionedComposition

**Comment by casiodbx** [comment]
@ppazos  me podrías explicar en que consiste este issue. Así me pongo con el. Muchas gracias

**Comment by ppazos** [comment]
@casiodbx la idea es agregar un link en el menú principal, solo para admins, a versionedComposition/index (controller: versionedComposition, action:index)

Ver: https://github.com/ppazos/cabolabs-ehrserver/blob/master/grails-app/controllers/common/change_control/VersionedCompositionController.groovy

Así el admin puede ver el listado de versiones (https://github.com/ppazos/cabolabs-ehrserver/blob/master/grails-app/views/versionedComposition/index.gsp)

Para que solo el admin vea el item en el menu, hay que hacer algo así:

 <sec:ifAnyGranted roles="ROLE_ADMIN">
     <li>
       <g:link controller="personIdType" action="index" class="${(controllerName=='personIdType')?'active':''}"><i class="glyphicon glyphicon glyphicon-tag"></i> <g:message code="desktop.idTypes" /></g:link>
    </li>
</sec:ifAnyGranted>

En: https://github.com/ppazos/cabolabs-ehrserver/blob/master/grails-app/views/layouts/admin.gsp

**Comment by ppazos** [comment]
Done.
