### ISSUE TITLE
Document the API using swagger

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#238]
http://swagger.io/

**Comment by casiodbx** [comment]
@ppazos Me pongo con ella mañana. Y cualquier duda te voy comentado.

**Comment by casiodbx** [comment]
A RESTful API documentation plugin for the Grails web application framework. Very much inspired by Swagger API documentation, this plugin reuses the available information of Grails Domain classes and Controllers to minimize documentation effort and to improve consistency.:
    http://grails.org/plugin/restapidoc
Proyecto en github:
    https://github.com/siemens/restapidoc
Ejemplo en el que se ha utilizado (Aunque viene en el anterior enlace, por si no lo encuentras):
    https://github.com/muenchhausen/HalTest

Yo me bajare el ejemplo y voy a evaluar como se puede adaptar al proyecto. Cualquier cosa te voy comentando.

**Comment by ppazos** [comment]
@casiodbx está ok si usas el plugin, lo único que debería tenerse cuidado es que se pueda acceder al código fuente de la documentación en el formato de Swagger, eso nos va a permitir integrarnos con otras herramientas luego, aparte de tener la documentación de la API.

**Comment by casiodbx** [comment]
@ppazos ya casí he generado el archivo swagger. Como te comente en un correo lo he hecho en un proyecto aparte. Espero la semana que viene poder integrarlo en EHRServer. En cuanto lo termine te aviso y me comentas que te parece.

**Comment by ppazos** [comment]
@casiodbx he limpiado algo de código, sacando clases y librerías que no se usan. Luego intenta bajarte el master para actualizar tu branch y ver que nada se rompió del lado de swagger :)

**Comment by ppazos** [comment]
Updated the files generated by @casiodbx to the new version of the API. This is WIP.


[swagger.zip](https://github.com/ppazos/cabolabs-ehrserver/files/1050651/swagger.zip)
