### ISSUE TITLE
Maven Problem 

### ISSUE THREAD

**Issue by tiger316** [ppazos/cabolabs-ehrserver#293]
Hi 

when i tried to build the cabolabs-ehrserver-0.5 and update the maven project 
i get error in these lines : 
 <plugin>
                <groupId>org.grails</groupId>
                <artifactId>grails-maven-plugin</artifactId>
                <version>2.4.4</version>
                <configuration>
                    <grailsVersion>${grails.version}</grailsVersion>
                </configuration>
                <extensions>true</extensions>
</plugin>

the Error Description:	

Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.4.4:config-directories (execution: default-config-directories, phase: generate-sources)	

Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.4.4:init (execution: default-init, phase: initialize)

Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.4.4:maven-compile (execution: default-maven-compile, phase: compile)

Plugin execution not covered by lifecycle configuration: org.grails:grails-maven-plugin:2.4.4:validate (execution: default-validate, phase: validate)

How to fix this ?

**Comment by ppazos** [comment]
@tiger316 just found that the pom file was outdated. I don't use maven to build the project, just use Grails directly, but generated the pom some time ago, I think when testing cloud servers that use the pom to build the project.

I updated the file manually but didn't tested it, please let me know if this works: https://github.com/ppazos/cabolabs-ehrserver/commit/a52de2daa611fc0d6fadb119c1211230adae7a8f

**Comment by tiger316** [comment]
Hi Pablo

Thanks for the fast replay 
unfortunately it didn't works i have the same error but instead of 2.4.4 i got 2.4.6  

can you till me the steps of building it by Grails 
i already read EHRServer v0.5 guide but some how it was not enough description for me to run the server 

Thanks for your help

**Comment by tiger316** [comment]
Hi Pablo 

i tried to run it by grails i am usin grails 3.1.1
but it give me exception in the attachment

| Error Error occurred running Grails CLI: null (NOTE: Stack trace has been fil
ered. Use --verbose to see entire trace.)
java.lang.NullPointerException
        at org.grails.cli.GrailsCli.initializeProfile(GrailsCli.groovy:504)
        at org.grails.cli.GrailsCli.initializeApplication(GrailsCli.groovy:308)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: null

![capture](https://cloud.githubusercontent.com/assets/15309652/13253989/d7f947ba-da47-11e5-9a35-092ce7d97b69.PNG)

**Comment by JDSBCC** [comment]
Hi,
Im with the same problem. First i tried to run with eclipse and i got maven problem. Next i run it in command line and I fixed Grails Cli:null installing grails 2.5.3.
Running "grails compile" is ok, however trying run.bat i got this error:
![capture](https://cloud.githubusercontent.com/assets/5583794/13255902/460d9006-da40-11e5-9fa1-8e37f062463e.PNG)
How can I fix this?

Thanks

**Comment by ppazos** [comment]
@tiger316 this is a Grails 2.5.3 app, won't work with 3.x.x

Please try downloading that version, then run grails -Dserver.port=8090 run-app


@JDSBCC can you copy the full trace of the exception here?

Also please try grails clean before grails run-app (maybe there is garbage from the intent of building against Grails 3.x).

**Comment by JDSBCC** [comment]
Hi,

grails clean didnt work. Here is the full trace:
![capture1](https://cloud.githubusercontent.com/assets/5583794/13258680/0f4199e4-da4c-11e5-96b5-0a4c140f4c2a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5583794/13258688/167d5e8c-da4c-11e5-9923-6776de79121a.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5583794/13258694/19f5b302-da4c-11e5-8408-56184193c3cc.PNG)

Thanks

**Comment by JDSBCC** [comment]
I already fix the problem. I forgot to create a database named ehrserver.

Thanks for your help

**Comment by JDSBCC** [comment]
When I try to register a user I got this error now:
![capture](https://cloud.githubusercontent.com/assets/5583794/13259217/5d46f7d6-da4e-11e5-9b51-abb2997b8b93.PNG)

I need to add something more to database?

**Comment by ppazos** [comment]
@JDSBCC yes, it was the database :D

About the latest issue, I forgot to add the setup of the needed environment variables to the docs, I'll do this for the v0.6 release (very soon!).
Those variables allow to send email notifications when a user registers, see: https://github.com/ppazos/cabolabs-ehrserver/blob/master/grails-app/conf/Config.groovy

```
grails {
   mail {
     host = System.getenv('EHRSERVER_EMAIL_HOST')
     port = System.getenv('EHRSERVER_EMAIL_PORT')
     username = System.getenv('EHRSERVER_EMAIL_USER')
     password = System.getenv('EHRSERVER_EMAIL_PASS')
     'default' {
        from = System.getenv('EHRSERVER_EMAIL_FROM')
     }
```

host is the URL or IP of an email provider, for example you can use gmail: https://www.siteground.com/kb/google_free_smtp_server/

or an alternative: 
http://www.easy-smtp.com/
https://sendpulse.com/smtp
https://www.mailjet.com/feature/smtp-relay/


If that doesn't work, it is not required to use the EHRServer, because we create a couple of test users by default, you can login using:
( username / password / organization )
admin / admin / 6666
orgman / orgman / 1234


The email config will fail only when a user tries to register.

**Comment by tiger316** [comment]
Hi 

when i used Grails 2.5.3 it started to works 
i faced the same problem that  @JDSBCC  has 
and thanks to him i create an empty DB called "ehrserver"

but i faced another problem but it didn't effect the running of the server 

Thanks both :)

**Comment by ppazos** [comment]
@tiger316 you might saw some error messages from the database, that is an issue with Grails, but as you say, doesn't affect the EHRServer.

I'll close this issue, if you find anything else, please open a new one. Thanks for trying the EHRServer!
