### ISSUE TITLE
Create endpoints to create/edit people or EHRs 

### ISSUE THREAD

**Issue by roliveira29** [ppazos/cabolabs-ehrserver#295]
Is there a way to create a person and his EHR with the REST API, something like a POST for subjectID that creates an EHR ?

**Comment by ppazos** [comment]
@roliveira29 not yet, we will keep this issue as a reminder to add those endpoints to the API.

**Comment by ppazos** [comment]
TBD:

1. URL mapping from POST /createPerson to POST /person
2. Add test cases to integration test

@roliveira29 ^

Parameters of the endpoint:

> String firstName // mandatory
> String lastName // mandatory
> String dob // format yyyyMMdd, mandatory
> String sex // M, F, U, mandatory
> String idCode // optional
> String idType  // optional
> String role // pat or doc, mandatory
> String organizationUid // mandatory, one of the org uids on your profile (get it from GET /profile)
> boolean createEhr // for role = pat if true, creates the patient's EHR
> String format // json or xml

**Comment by ppazos** [comment]
@roliveira29 done!
