### ISSUE TITLE
Problem creating new folder

### ISSUE THREAD

**Issue by JDSBCC** [ppazos/cabolabs-ehrserver#324]
Hi,
Im trying to create a new folder in the directory menu, but I always get this error:

![capture](https://cloud.githubusercontent.com/assets/5583794/14353235/1baff0d0-fcd0-11e5-8aaf-7fc0a70ff00a.PNG)

What am I doing wrong?

Thanks

**Comment by ppazos** [comment]
@JDSBCC thanks for reporting, I'll take a look at this tomorrow. I think it will be an easy fix.

**Comment by JDSBCC** [comment]
Taking this oportunity, Im building a solution which index data from ehr and all the data is provided by another database, so I  need a process that maps one database to another. 

My doubt is, how can I commit data to ehr using the rest api?
I already created a new template using Template Designer, however I dont understand how I fill it with data.

**Comment by ppazos** [comment]
@JDSBCC I have two other apps that commit data to the EHRServer, check the code here:

https://github.com/ppazos/EHRCommitter
https://github.com/ppazos/cabolabs-emrapp

You can test on our staging environment:

https://cabolabs-ehrserver.rhcloud.com/ehr (create an account)
http://committer-ehrserver.rhcloud.com/committer (use the same credentials as the EHRServer)


Also, you can find the API docs here: http://cabolabs.com/en/projects

**Comment by ppazos** [comment]
@JDSBCC couldn't find the failing code on master. Did you downloaded the latest master or a previous tag/version?
Also, this is working OK on staging: https://cabolabs-ehrserver.rhcloud.com/ehr

**Comment by JDSBCC** [comment]
I tried with the version v0.5 and v0.6 locally. I will try with latest master version.

Thanks

**Comment by ppazos** [comment]
@JDSBCC thanks, that looks like a leftover from a refactor I did some time ago. Please try with master: https://github.com/ppazos/cabolabs-ehrserver/archive/master.zip

**Comment by JDSBCC** [comment]
Yes, you are right, there is no problem with latest master version. 
Just a question, as I said before Im trying to commit data via rest API. This is the right place to make questions about or there is some forum where can I ask?

Thanks and sorry for false alarm xD

**Comment by ppazos** [comment]
@JDSBCC you can drop questions on github issues, no worries :)
