### ISSUE TITLE
unknown error and Timed out (configurable in settings)

### ISSUE THREAD

**Issue by JDSBCC** [ppazos/cabolabs-ehrserver#356]
Hi again =),
With your help in the other issue, I finnaly concluded my application. However there are some few problems that appear sometimes and I dont know what they are. So, first problem is this: 
![error](https://cloud.githubusercontent.com/assets/5583794/15780832/636a16e2-299b-11e6-97b8-80d88927a983.PNG)
I think this error appear when I try to commit persons by REST API using **createPerson**, but Im not really sure about it.
The second is **ERROR: Timed out (configurable in settings)**. This is a request error and just happens when I try to do a lot of request at the same time (im using threads, thats why this happen). My questions about this error are: where can I configure this option? Can I make this time infinite? Or this happens for another reason?

Btw Im not using the last version of EhrServer, Im using some version you commit in april I think xD

Thanks in advance

**Comment by ppazos** [comment]
Hi @JDSBCC the XML warnings don't affect the functionality of the system. It is an internal issue of the XML processing on Groovy, that also depends on an issue on SAX. I think those can be turned off but it needs some research to find how.

Timeouts in general depend on the machine capabilities, if if runs out of memory of if there are a lot of reads/writes waiting for to execute on the database, that will trigger timeouts, faster servers (CPU), with more memory (RAM) and faster disks (SSD) will support more requests per second and trigger less timeouts, but all resources are finite, if you push your server to the limit, you will start seeing timeouts. The duration of the timeout in general is a configuration of the web server. If you are using tomcat to deploy the EHRServer, check https://tomcat.apache.org/tomcat-7.0-doc/config/http.html

It would be useful to know what are the characteristics of the machine you are running the EHRServer on and what is the number of request you send in parallel until you receive the first timeout.

Also, when you call a service it is recommended to avoid send-and-forget. Your script should check for error conditions and try again if a communication error occurred (timeout or other connection error).

With the information provided, I would say these are not EHRServer issues per-se.

**Comment by JDSBCC** [comment]
Ok thank you. It doesnt matter what are the characteristics of the machine, because with my current code probably it will give timeout in any other machine. I just see now that I have no restrictions in requests quantity, so when I start my program I probably have more than 50 requests, if it doesnt crash before xD
And yes im doing just like you said send-and-forget, but i'll fix it.

sorry for posting an error that is not directly related to EHRServer and thanks again =)

**Comment by ppazos** [comment]
@JDSBCC no problem at all, you can't know if there is a problem of the EHRServer or not without asking :)

I prefer you ask so I can detect if there are any real issues, and if those are not EHRServer issues, I'm still happy to help with things related to it's use.
