### ISSUE TITLE
Inconsistent result for GET /patients endpoint

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#413]
We added an object to return a list and pagination information in JSON from the GET /patients endpoint.

The problem is that sometimes the JSON marshaller of the object is executed OK and sometimes the object is marshalled to JSON without executing the custom marshaller, so the structure returned is different making client apps fail randomly.

![screen shot 2016-09-09 at 12 49 51 am](https://cloud.githubusercontent.com/assets/1278556/18374933/b23f7f7c-7627-11e6-9335-42b8a3562984.png)

The expected is the list of patients to be named 'patients' but when the marshaller is not executed, it returns the internal 'list'.

The marshaller is here: https://github.com/ppazos/cabolabs-ehrserver/blob/master/grails-app/conf/BootStrap.groovy#L372-L385

**Comment by pvidasoftware** [comment]
Can you capture the requests (from network tab) ? maybe something in the headers can be the trick

**Comment by ppazos** [comment]
I deployed a new version and the problem seemed to go away. This was weird.

TODO: write test to check for the right object structure as a result of the REST API calls.

**Comment by ppazos** [comment]
Done.
