### ISSUE TITLE
EHRServer_v0.5.pdf manual login details incorrect

### ISSUE THREAD

**Issue by danleahy** [ppazos/cabolabs-ehrserver#417]
I am working off EHRServer_v0.5.pdf

Just did a manual install of EHRServer using the instructions in 
EHRServer v0.5 guide

using the latest development source code from the master branch

login details did't include the organisation name

it said to use admin and admin, checking the bootstrap.groovy and the DB i can see the organisation is set to 
Hospital de Clinicas

for the admin user

I get this error when i try to use the admin user and the organisation above

2016-09-16 17:18:43,767 [http-bio-8090-exec-9] INFO  security.AuthProvider  - Authentication failed - organization doesnt exists

What login details should i be using to get into the admin view ?

**Comment by ppazos** [comment]
@danleahy please use the v0.7 guide, v0.5 is quite old, check it here http://www.cabolabs.com/en/projects

BTW, on the guide folder of the master branch you will find the current guide that is updated for the next version, but is work in progress. Still, is accurate if you are using the master branch of the project.

**Comment by danleahy** [comment]
Hi Pablo, 
             thanks for that, i successfully logged in there on my local instance, on my local machine its fairly slow to load. I am taking a look at EHRServer to see if we can setup a virtual EHR system here in UCD for the ARCH project www.arch.ie . I will more time in october to look at this properly. Thanks again.

**Comment by ppazos** [comment]
@danleahy I'm glad to help, let me know if I can do anything else for you. Also I'm interested in the project, please let me know where I can find more info about the specific requirements for the virtual EHR. Thanks!

**Comment by ppazos** [comment]
@danleahy how can I contact you? I want to send you info about the next steps of the EHRServer. You can drop me a line at pablo.pazos@cabolabs.com
