### ISSUE TITLE
HTTP status code: 0  request login by api

### ISSUE THREAD

**Issue by jeanmalves** [ppazos/cabolabs-ehrserver#420]
I'm using server ehrserver, i created my account. When i'm going to request by POST authentication token the return is HTTP status code: 0.

I'm using the url: https://ehrserver.cabolabs.com/ehr/rest/login

**Comment by ppazos** [comment]
@jeanmalves on the latest deployment on the cloud (our test server) the EHRServer was deployed to the root context, so the /ehr is no needed any more, try: https://ehrserver.cabolabs.com/rest/login

**Comment by jeanmalves** [comment]
@ppazos I tried your sugestion, but not work. Follow my url:

https://ehrserver.cabolabs.com/rest/login?username=someuser&password=mypass&organization=684795

**Comment by ppazos** [comment]
@jeanmalves sorry, the base URL is incorrect, it is: https://cabolabs-ehrserver.rhcloud.com

Please check the guide on page 4: http://cabolabs.com/en/projects

**Comment by jeanmalves** [comment]
It's work! I saw this url at the guide, but i thought this url was just sign up or login because have a section about API.

Tank you.
