### ISSUE TITLE
Upgrade to Grails3

### ISSUE THREAD

**Issue by dngferreira** [ppazos/cabolabs-ehrserver#421]
I'm a bit new to the grails ecosystem but if I understand correctly this project is developed using Grails 2.x and there is already a version 3 (which is a totally different beast). 
How hard would it be upgrade the version of grails to 3.x and are there any blockers for the upgrade?

**Comment by ppazos** [comment]
@dngferreira EHRServer is on 2.5.5, no plan for updating to 3.x, it really doesn't add any value to the project right now, and will require a lot of work.

**Comment by dngferreira** [comment]
Ok, good enough.
