### ISSUE TITLE
It should be possible to use Grails wrapper to run local instance

### ISSUE THREAD

**Issue by jaykola** [ppazos/cabolabs-ehrserver#438]
Grails via GrailsWrapper -- saves the 'tester' the hassle of downloading and install Grails separately.... It also prevents the headache if user already has a different version of Grails on their machine... I find Grails particularly painful with version conflicts....

**Comment by ppazos** [comment]
The app can be downloaded and the wrapper can be used. This is not related to EHRServer, is about Grails. Also Grails have a version manager that saves time, use SDKMAN.
