### ISSUE TITLE
Allow dev or local instance to use embedded H2 database instead of MySQL

### ISSUE THREAD

**Issue by jaykola** [ppazos/cabolabs-ehrserver#442]
MySQL installation should not be necessary if users just want to try a local instance of ehrserver. Making H2 the default database should remove this dependency.

**Comment by ppazos** [comment]
MySQL is the only completely tested database, and by default MySQL is recommended. Other dbs can be configured easily by defining custom environments in the Config.groovy, like dev_with_h2 or dev_witth_postgres. Who wants to grab this, should test the whole app against each new database.
