### ISSUE TITLE
Use fileUid for OPT file names

### ISSUE THREAD

**Issue by dngferreira** [ppazos/cabolabs-ehrserver#452]
The OperationalTemplateController action upload and show are not synchronized in what regards the filename that is created in the upload action and the filename that is searched for when using the show action.

With the demo files it works ok, looking at the filenames it seems that they were built using the concept field instead of the uid that is being used now in the upload action.

I can make the changes to the code and create a PR but I have doubts about what the change should be:
- Change the demo filenames to use the uid as file name?
- Change  the upload action to use the concept field as filename?
- Try to find a filename created using the uid and default to the concept one?

I prefer the first option, IMHO concept is a more generic field than the uid.

**Comment by ppazos** [comment]
Hi @dngferreira I'm changing the file naming strategy for all the files used by the EHRServer. I already updated the commits and versions to use a UUID generated by the EHRServer, the same will happen for the OPTs. As a design decision: no file in the file system should be named based on data controlled by external applications. OPTs, versions and commit logs fall under this category. With all the file names controlled by the EHRServer we avoid possible errors from client apps and keep naming consistent across multiple clients.

Check the class Commit, you will see a String fileUid field there, the same should be in the OperationalTemplateIndex, to store the OPT physical file name. The fileUid should be internal, so can't be used on views. The uid should be used instead. I need to check if the OPT uid is being assigned by the EHRServer or if we are taking it from the OPT. The problem with this uid is that is generated from different modeling tools and we can't control how that is generated, and there is a very low probability of having to repeated uids, depending on the uid generation (there are 4 or 5 types of uuids). I would prefer that the uid used in the API and in the UI to get OPTs is generated and controlled by the EHRServer. We can also store the uid generated by modeling tools as a reference, but not use it as a key for the OPTs.

**Comment by ppazos** [comment]
We are using the OPT UID as secondary key. That should be used to detect if the same OPT was uploaded twice. Now we are using the concept name to check for duplicates.

**Comment by ppazos** [comment]
Store and loading using the fileUid is working OK.

TODO:
1. rename existing base OPTs generating and storing fileUid for them
2. the upload overwrite should check the UID not the file name or the concept

**Comment by ppazos** [comment]
when overwriting, delete all and reindex all the OPTs and referenced indexes

**Comment by ppazos** [comment]
The only missing part is the renaming of predefined OPTs.

**Comment by ppazos** [comment]
Done.
