### ISSUE TITLE
Operational template XSD

### ISSUE THREAD

**Issue by dngferreira** [ppazos/cabolabs-ehrserver#501]
Hi, 
I'm trying understand the rules behind the operational template xsd that this project uses.
The one from [Java-libs](https://github.com/openEHR/java-libs/blob/master/oet-parser/src/main/xsd/Template.xsd) doesn't have a view element on the template.

Why are they different?

Best,
Duarte

**Comment by ppazos** [comment]
Template XSD isfor OET, we use OPT, the final structure for OET, that is exported from the template designer.
