### ISSUE TITLE
admin docker credetials?

### ISSUE THREAD

**Issue by jujes** [ppazos/cabolabs-ehrserver#593]
Hi, someone know admin or super user docker credentials?

**Comment by ppazos** [comment]
why do you need that?

**Comment by jujes** [comment]
hi @ppazos  because I deploy it locally in my laptop and need sign in to lookup how it work...

**Comment by ppazos** [comment]
@jujes if you deployed the ehrserver, you need the ehrserver credentials. Look ad the Bootstrap.groovy file where users are created, or follow the guide: https://www.cabolabs.com/en/projects pages 12/13
