### ISSUE TITLE
ERROR "hbm2ddl.SchemaExport" AFTER RUN GRAILS APP

### ISSUE THREAD

**Issue by johanromero** [ppazos/cabolabs-ehrserver#798]
I got this issue after run app : grails -Dserver.port=8091 run-app

Configuring Spring Security Core ...
... finished configuring Spring Security Core

| Error Sat Oct 28 16:50:22 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error Sat Oct 28 16:50:23 COT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
| Error 2017-10-28 16:50:29,753 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table api_key drop foreign key FK_206rwayp6mt8xlnk0opcvs9uh
| Error 2017-10-28 16:50:29,757 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.api_key' doesn't exist
| Error 2017-10-28 16:50:29,758 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table api_key drop foreign key FK_igm287ynn3c0yfn41xiy8ittm
| Error 2017-10-28 16:50:29,759 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.api_key' doesn't exist
| Error 2017-10-28 16:50:29,760 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table audit_details drop foreign key FK_c7w51994gcm1l5vx3u2ot5cq7
| Error 2017-10-28 16:50:29,761 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.audit_details' doesn't exist
| Error 2017-10-28 16:50:29,763 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table commit drop foreign key FK_n05fx10pj4eb25g1vk2q269xu
| Error 2017-10-28 16:50:29,766 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.commit' doesn't exist
| Error 2017-10-28 16:50:29,767 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table composition_index drop foreign key FK_b8hp8al4wn3ol079chbn59dmv
| Error 2017-10-28 16:50:29,768 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.composition_index' doesn't exist
| Error 2017-10-28 16:50:29,770 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table contribution drop foreign key FK_2wx9ki99erdwgehut0a8xd75o
| Error 2017-10-28 16:50:29,771 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.contribution' doesn't exist
| Error 2017-10-28 16:50:29,772 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table contribution drop foreign key FK_tbym5csoi8rixh3jora1tm8p4
| Error 2017-10-28 16:50:29,773 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.contribution' doesn't exist
| Error 2017-10-28 16:50:29,775 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table data_value_index drop foreign key FK_jdcg3xa50itrqiaaqrervgpaw
| Error 2017-10-28 16:50:29,776 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.data_value_index' doesn't exist
| Error 2017-10-28 16:50:29,778 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table data_value_index_log drop foreign key FK_l19nicaii33s2y4op4dn47w3
| Error 2017-10-28 16:50:29,779 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.data_value_index_log' doesn't exist
| Error 2017-10-28 16:50:29,781 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_boolean_index drop foreign key FK_7a3rtk2pukask0rakivlgr9wk
| Error 2017-10-28 16:50:29,782 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_boolean_index' doesn't exist
| Error 2017-10-28 16:50:29,783 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_coded_text_index drop foreign key FK_syr4kxbtk43kb5col63t6l7u5
| Error 2017-10-28 16:50:29,786 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_coded_text_index' doesn't exist
| Error 2017-10-28 16:50:29,787 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_count_index drop foreign key FK_nl8fjqngd31agt9upj5kbojqr
| Error 2017-10-28 16:50:29,789 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_count_index' doesn't exist
| Error 2017-10-28 16:50:29,790 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_date_index drop foreign key FK_9veqaco2f7xxax98lo1totpqx
| Error 2017-10-28 16:50:29,791 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_date_index' doesn't exist
| Error 2017-10-28 16:50:29,792 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_date_time_index drop foreign key FK_el7ynkj7rhy8sy9g1o241q2jo
| Error 2017-10-28 16:50:29,793 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_date_time_index' doesn't exist
| Error 2017-10-28 16:50:29,797 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_duration_index drop foreign key FK_fpiwxwhjafu0p8f4ql4oomkx0
| Error 2017-10-28 16:50:29,798 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_duration_index' doesn't exist
| Error 2017-10-28 16:50:29,800 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_identifier_index drop foreign key FK_frksocua8hhqpyl6l6fsw1ywl
| Error 2017-10-28 16:50:29,802 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_identifier_index' doesn't exist
| Error 2017-10-28 16:50:29,804 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_multimedia_index drop foreign key FK_poqnr9hh7rwy17ofrp886n6e8
| Error 2017-10-28 16:50:29,807 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_multimedia_index' doesn't exist
| Error 2017-10-28 16:50:29,810 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_ordinal_index drop foreign key FK_qd4q8ls750v92j5bg658w3leu
| Error 2017-10-28 16:50:29,811 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_ordinal_index' doesn't exist
| Error 2017-10-28 16:50:29,813 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_parsable_index drop foreign key FK_s1720qaa2499xsqfme3m1wqv7
| Error 2017-10-28 16:50:29,814 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_parsable_index' doesn't exist
| Error 2017-10-28 16:50:29,818 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_proportion_index drop foreign key FK_li9fmrr8a7fcsjva9ldkcyq5
| Error 2017-10-28 16:50:29,819 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_proportion_index' doesn't exist
| Error 2017-10-28 16:50:29,822 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_quantity_index drop foreign key FK_gg0xer64advv0il2hor6yc0qk
| Error 2017-10-28 16:50:29,823 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_quantity_index' doesn't exist
| Error 2017-10-28 16:50:29,826 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table dv_text_index drop foreign key FK_1evqk954cgdnxqjacdie1yeq3
| Error 2017-10-28 16:50:29,827 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.dv_text_index' doesn't exist
| Error 2017-10-28 16:50:29,829 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table ehr drop foreign key FK_9knfes3go48p8cfl70f40fq66
| Error 2017-10-28 16:50:29,831 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.ehr' doesn't exist
| Error 2017-10-28 16:50:29,833 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table ehr drop foreign key FK_cbi85wn65sqb290xysh25h8ca
| Error 2017-10-28 16:50:29,834 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.ehr' doesn't exist
| Error 2017-10-28 16:50:29,835 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table folder drop foreign key FK_9u26l7mcb559isqdqnh7cefyx
| Error 2017-10-28 16:50:29,837 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.folder' doesn't exist
| Error 2017-10-28 16:50:29,839 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table folder_template_folder_template_item drop foreign key FK_o3798gxy7s0to5qi6bk9s5rf8
| Error 2017-10-28 16:50:29,841 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.folder_template_folder_template_item' doesn't exist
| Error 2017-10-28 16:50:29,843 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table folder_template_item_folder_template_item drop foreign key FK_8llvvuarhjmyqshrneidcx9mw
| Error 2017-10-28 16:50:29,844 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.folder_template_item_folder_template_item' doesn't exist
| Error 2017-10-28 16:50:29,848 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table locatable_ref_index drop foreign key FK_6it3ovqtmaqrm6hfvh7vlftji
| Error 2017-10-28 16:50:29,850 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.locatable_ref_index' doesn't exist
| Error 2017-10-28 16:50:29,852 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table notification_status drop foreign key FK_k9n0gkxmhp5s9c96yuyqf6feu
| Error 2017-10-28 16:50:29,853 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.notification_status' doesn't exist
| Error 2017-10-28 16:50:29,855 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table notification_status drop foreign key FK_q9yujh8c755vwck3dknavkg0j
| Error 2017-10-28 16:50:29,857 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.notification_status' doesn't exist
| Error 2017-10-28 16:50:29,859 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table operational_template_index_operational_template_index_item drop foreign key FK_rt96qvisq0x6tsirktum44nod
| Error 2017-10-28 16:50:29,860 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.operational_template_index_operational_template_index_item' doesn't exist
| Error 2017-10-28 16:50:29,862 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table operational_template_index_operational_template_index_item drop foreign key FK_mfj903nxqk0gj85gb7ulodtsj
| Error 2017-10-28 16:50:29,864 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.operational_template_index_operational_template_index_item' doesn't exist
| Error 2017-10-28 16:50:29,866 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table operational_template_index_referenced_archetype_nodes drop foreign key FK_byqcjj2bh63pq8w74kdwe5guc
| Error 2017-10-28 16:50:29,868 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.operational_template_index_referenced_archetype_nodes' doesn't exist
| Error 2017-10-28 16:50:29,871 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table operational_template_index_referenced_archetype_nodes drop foreign key FK_nhyi0ep06mtlhpfxmd5edxhae
| Error 2017-10-28 16:50:29,872 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.operational_template_index_referenced_archetype_nodes' doesn't exist
| Error 2017-10-28 16:50:29,874 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table operational_template_index_share drop foreign key FK_8i8jboeroowjpbusn9h1fikfu
| Error 2017-10-28 16:50:29,876 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.operational_template_index_share' doesn't exist
| Error 2017-10-28 16:50:29,879 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table operational_template_index_share drop foreign key FK_kf3n5kc81bpcugbr1596fdpd2
| Error 2017-10-28 16:50:29,880 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.operational_template_index_share' doesn't exist
| Error 2017-10-28 16:50:29,882 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table plan_association drop foreign key FK_kdgvduo08ght3nmsd735f2jj4
| Error 2017-10-28 16:50:29,883 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.plan_association' doesn't exist
| Error 2017-10-28 16:50:29,885 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table query drop foreign key FK_4kmmdrtmbkline1yx88l528b
| Error 2017-10-28 16:50:29,888 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.query' doesn't exist
| Error 2017-10-28 16:50:29,889 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table query_data_criteria drop foreign key FK_nn5ecv2ljvvixddjfpj6wq2xk
| Error 2017-10-28 16:50:29,890 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.query_data_criteria' doesn't exist
| Error 2017-10-28 16:50:29,892 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table query_data_get drop foreign key FK_17ved4ttowskvdplsxkaqavgr
| Error 2017-10-28 16:50:29,892 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.query_data_get' doesn't exist
| Error 2017-10-28 16:50:29,894 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table query_share drop foreign key FK_tkgj8kdymggd5sg592jfb92gj
| Error 2017-10-28 16:50:29,894 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.query_share' doesn't exist
| Error 2017-10-28 16:50:29,896 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table query_share drop foreign key FK_pcavoxmpm03kh9lnx208ce2hc
| Error 2017-10-28 16:50:29,898 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.query_share' doesn't exist
| Error 2017-10-28 16:50:29,900 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table string_index drop foreign key FK_7oes4hqpbiysnkfyxeqk3lw6p
| Error 2017-10-28 16:50:29,901 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.string_index' doesn't exist
| Error 2017-10-28 16:50:29,903 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table user_role drop foreign key FK_apcc8lxk2xnug8377fatvbn04
| Error 2017-10-28 16:50:29,903 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.user_role' doesn't exist
| Error 2017-10-28 16:50:29,904 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table user_role drop foreign key FK_it77eq964jhfqtu54081ebtio
| Error 2017-10-28 16:50:29,906 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.user_role' doesn't exist
| Error 2017-10-28 16:50:29,909 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table user_role drop foreign key FK_998a3yue1lj8haalbtcvtslux
| Error 2017-10-28 16:50:29,910 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.user_role' doesn't exist
| Error 2017-10-28 16:50:29,912 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table version drop foreign key FK_q3m84ka7rlrj0vf4t1ru2bcvh
| Error 2017-10-28 16:50:29,914 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.version' doesn't exist
| Error 2017-10-28 16:50:29,915 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table version drop foreign key FK_p1nho9icmidq1ik80spha2s5w
| Error 2017-10-28 16:50:29,918 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.version' doesn't exist
| Error 2017-10-28 16:50:29,919 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table version drop foreign key FK_qku5pv15ayvcge2p64ko7cvb4
| Error 2017-10-28 16:50:29,921 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.version' doesn't exist
| Error 2017-10-28 16:50:29,922 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table versioned_composition drop foreign key FK_kkyigtfbihs8x2lafmxhicfcg
| Error 2017-10-28 16:50:29,923 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.versioned_composition' doesn't exist
| Error 2017-10-28 16:50:50,567 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Spring security stateles secretKey not configured or empty. Please, set 'grails.plugin.security.stateless.secretKey' value in your Config.groovy
Message: Spring security stateles secretKey not configured or empty. Please, set 'grails.plugin.security.stateless.secretKey' value in your Config.groovy
    Line | Method
->>  131 | doCall    in SecurityStatelessGrailsPlugin$_closure2
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    266 | run       in java.util.concurrent.FutureTask
|   1149 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    624 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run . . . in java.lang.Thread

**Comment by ppazos** [comment]
Good the first error I would need your data source file to check your config, there is an issue with SSL as the error says.

For the last error you need to set the secret as it is stated on the error itself.

**Comment by johanromero** [comment]
[conf.zip](https://github.com/ppazos/cabolabs-ehrserver/files/1425328/conf.zip)
Hi Pablo!

I attached my datasource files config. 
I've already set up the secret key with the sample key provided. 

Thanks!!!!

**Comment by ppazos** [comment]
@johanromero try adding ?useSSL=false at the end of the connection string for development environment

it is strange I can't reproduce the error, I'm using MySQL 5.6.

BTW, which version of Grails do you have installed?

**Comment by johanromero** [comment]
My environment: 

Grails version: 2.5.6
MySql version:  5.6.38;
java version "1.8.0_151"
Windows 10 pro.

Cheers!

**Comment by johanromero** [comment]
Yes I did.

**Comment by ppazos** [comment]
What happened? Did the error changed? Did the app work?

**Comment by ppazos** [comment]
Is the app working? are the tables created in the database?

Those errors are known issues of logging of Grails/MySQL connector. Not real errors.

**Comment by johanromero** [comment]
Unfortunately neither tables and app are working. There is no tables. Could I use another approach to connect to mysql instead of jdbc and this mapping: 
    driverClassName = 'com.mysql.jdbc.Driver'
    dialect = org.hibernate.dialect.MySQL5InnoDBDialect
Thanks!!

**Comment by ppazos** [comment]
Can you share the current logs from the run-app and your Datasource.groovy?

**Comment by johanromero** [comment]
I finally fixed my error setting another secretkey password:
grails.plugin.security.stateless.secretKey = 'mysuperhipermegakey'

**Comment by ppazos** [comment]
It is recommended that to be an environment variable, not a hardcoded value using

`grails.plugin.security.stateless.secretKey = System.getenv('EHRSERVER_REST_SECRET') `
