### ISSUE TITLE
Getting error 'versions should have one or more items and has none' while committing composition.

### ISSUE THREAD

**Issue by saurabhrasp** [ppazos/cabolabs-ehrserver#819]
I am new to openehr platform.
Actually, i am trying to commit a sample composition into ehrserver using rest client insomnia.

i am getting below error.

`<result>
	<type>AR</type>
	<message>versions should have one or more items and has none</message>
	<code>EHR_SERVER::API::RESPONSE_CODES::402.1</code>
</result>`

i created two sample archetypes and one template for supporting this commit, these are attached.

[archetypes.zip](https://github.com/ppazos/cabolabs-ehrserver/files/1542401/archetypes.zip)

My xml body for composition commit post request is given below.

[survery_question_composition.txt](https://github.com/ppazos/cabolabs-ehrserver/files/1542420/survery_question_composition.txt)

Please guide me what is the problem and where i am wrong.

**Comment by ppazos** [comment]
Please check the guide, it has an example of the xml used for the commit.

**Comment by ppazos** [comment]
@saurabhrasp you are missing the versions element on the XML. Please check the guide.
