### ISSUE TITLE
"Test Insomnia Script" link is getting a 404

### ISSUE THREAD

**Issue by johanromero** [ppazos/cabolabs-ehrserver#825]
404 at https://github.com/ppazos/cabolabs-ehrserver/blob/master/ehrserver_rest_insomnia.json
I'm reading this guide: 
https://cloudehrserver.com/learn/data_commit

**Comment by ppazos** [comment]
@johanromero please check the base URL used, you need to change that to point to your server.

**Comment by johanromero** [comment]
Where do I find this file: "ehrserver_rest_insomnia.json"??

**Comment by ppazos** [comment]
@johanromero check the api folder in the project
