### ISSUE TITLE
facing issue while uploading opt template in Cabolabs server.

### ISSUE THREAD

**Issue by saurabhrasp** [ppazos/cabolabs-ehrserver#873]
i am facing issue while uploading opt template in Cabolabs server, Its not throwing any error but doing nothing also.
But that template is showing into template list and when we click on that template its throwing internal server error.
![image](https://user-images.githubusercontent.com/23055899/36774773-6a29e9c4-1c85-11e8-821f-2ab459a72456.png)

**Comment by ppazos** [comment]
@saurabhrasp is this still happening? I fixed this issue a couple of  days ago. Please try again and let me know it this is currently happening. thanks!
