### ISSUE TITLE
How to upload any document or scanned image with any composition while committing.

### ISSUE THREAD

**Issue by saurabhrasp** [ppazos/cabolabs-ehrserver#886]
Pablo, we have requirement to upload some document/scanned images with a composition while committing to cabolabs ehrserver.
we also need to upload document(s) while creating other versions.
Please suggest how we can achieve this functionality with cabolabs ehrserver.

**Comment by ppazos** [comment]
@saurabhrasp compositions are documents, and each commit can contain many documents. Not sure if that is the question.

To store images in openEHR there is the DV_MULTIMEDIA datatype. I can create a small guide on how to use that datatype in XML.

**Comment by ppazos** [comment]
@saurabhrasp I'm building a guide on how to add images to a composition, this is work in progress but might help https://cloudehrserver.com/learn/xml_guides/dv_multimedia_xml
