### ISSUE TITLE
Throwing error while configuring cabolabs ehrserver locally on our server.

### ISSUE THREAD

**Issue by saurabhrasp** [ppazos/cabolabs-ehrserver#904]
Pablo,

i am configuring ehrserver locally on our server, and following instructions mentioned in below pdf file from page 11.
https://docs.google.com/viewerng/viewer?url=https://cabolabs.com/software_resources/EHRServer_v1.0.pdf

But when we ran below command then its showing various errors.
`> ehrserver/ grails -Dserver.port=8090 run-app`
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Errors-**

rt  - Table 'ehrserver.account' doesn't exist
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table api_key drop foreign key FK_206rwayp6
mt8xlnk0opcvs9uh
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.api_key' doesn't exist
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table api_key drop foreign key FK_igm287ynn
3c0yfn41xiy8ittm
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.api_key' doesn't exist
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table audit_details drop foreign key FK_c7w
51994gcm1l5vx3u2ot5cq7
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.audit_details' doesn't exist
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table commit drop foreign key FK_n05fx10pj4
eb25g1vk2q269xu
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.commit' doesn't exist
| Error 2018-03-13 11:12:42,091 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table composition_index drop foreign key FK
_b8hp8al4wn3ol079chbn59dmv
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.composition_index' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table configuration_item drop foreign key F
K_nhx9wax9i7vc78wjq1oq0yd67
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.configuration_item' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table configuration_item drop foreign key F
K_offpbb7p9farr2lr6iav4fmpb
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.configuration_item' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table contribution drop foreign key FK_2wx9
ki99erdwgehut0a8xd75o
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.contribution' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table contribution drop foreign key FK_tbym
5csoi8rixh3jora1tm8p4
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.contribution' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table data_value_index drop foreign key FK_
jdcg3xa50itrqiaaqrervgpaw
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.data_value_index' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table data_value_index_log drop foreign key
 FK_l19nicaii33s2y4op4dn47w3
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.data_value_index_log' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_boolean_index drop foreign key FK_
7a3rtk2pukask0rakivlgr9wk
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_boolean_index' doesn't exist
| Error 2018-03-13 11:12:42,107 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_coded_text_index drop foreign key
FK_syr4kxbtk43kb5col63t6l7u5
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_coded_text_index' doesn't exist
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_count_index drop foreign key FK_nl
8fjqngd31agt9upj5kbojqr
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_count_index' doesn't exist
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_date_index drop foreign key FK_9ve
qaco2f7xxax98lo1totpqx
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_date_index' doesn't exist
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_date_time_index drop foreign key F
K_el7ynkj7rhy8sy9g1o241q2jo
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_date_time_index' doesn't exist
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_duration_index drop foreign key FK
_fpiwxwhjafu0p8f4ql4oomkx0
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_duration_index' doesn't exist
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_identifier_index drop foreign key
FK_frksocua8hhqpyl6l6fsw1ywl
| Error 2018-03-13 11:12:42,122 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_identifier_index' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_multimedia_index drop foreign key
FK_poqnr9hh7rwy17ofrp886n6e8
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_multimedia_index' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_ordinal_index drop foreign key FK_
qd4q8ls750v92j5bg658w3leu
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_ordinal_index' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_parsable_index drop foreign key FK
_s1720qaa2499xsqfme3m1wqv7
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_parsable_index' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_proportion_index drop foreign key
FK_li9fmrr8a7fcsjva9ldkcyq5
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_proportion_index' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_quantity_index drop foreign key FK
_gg0xer64advv0il2hor6yc0qk
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_quantity_index' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table dv_text_index drop foreign key FK_1ev
qk954cgdnxqjacdie1yeq3
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.dv_text_index' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table ehr drop foreign key FK_9knfes3go48p8
cfl70f40fq66
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.ehr' doesn't exist
| Error 2018-03-13 11:12:42,138 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table ehr drop foreign key FK_cbi85wn65sqb2
90xysh25h8ca
| Error 2018-03-13 11:12:42,153 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.ehr' doesn't exist
| Error 2018-03-13 11:12:42,153 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table ehr_query_query drop foreign key FK_p
wc7b26mm8xq8f8d3hl45vii3
| Error 2018-03-13 11:12:42,153 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.ehr_query_query' doesn't exist
| Error 2018-03-13 11:12:42,153 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table folder drop foreign key FK_9u26l7mcb5
59isqdqnh7cefyx
| Error 2018-03-13 11:12:42,153 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.folder' doesn't exist
| Error 2018-03-13 11:12:42,153 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table folder_template_folder_template_item
drop foreign key FK_o3798gxy7s0to5qi6bk9s5rf8
| Error 2018-03-13 11:12:42,169 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.folder_template_folder_template_item' doesn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table folder_template_item_folder_template_
item drop foreign key FK_8llvvuarhjmyqshrneidcx9mw
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.folder_template_item_folder_template_item' doesn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table locatable_ref_index drop foreign key
FK_6it3ovqtmaqrm6hfvh7vlftji
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.locatable_ref_index' doesn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table notification_status drop foreign key
FK_k9n0gkxmhp5s9c96yuyqf6feu
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.notification_status' doesn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table notification_status drop foreign key
FK_q9yujh8c755vwck3dknavkg0j
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.notification_status' doesn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table operational_template_index_operationa
l_template_index_item drop foreign key FK_rt96qvisq0x6tsirktum44nod
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.operational_template_index_operational_template_index_ite
m' doesn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table operational_template_index_operationa
l_template_index_item drop foreign key FK_mfj903nxqk0gj85gb7ulodtsj
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.operational_template_index_operational_template_index_ite
m' doesn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table operational_template_index_referenced
_archetype_nodes drop foreign key FK_byqcjj2bh63pq8w74kdwe5guc
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.operational_template_index_referenced_archetype_nodes' do
esn't exist
| Error 2018-03-13 11:12:42,185 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table operational_template_index_referenced
_archetype_nodes drop foreign key FK_nhyi0ep06mtlhpfxmd5edxhae
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.operational_template_index_referenced_archetype_nodes' do
esn't exist
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table organization drop foreign key FK_4aj3
cf70hviyfp7k0ltkhsmcd
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.organization' doesn't exist
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table plan_association drop foreign key FK_
f8vvs5rkrcgbmgsvrmy8agb
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.plan_association' doesn't exist
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table plan_association drop foreign key FK_
kdgvduo08ght3nmsd735f2jj4
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.plan_association' doesn't exist
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table query drop foreign key FK_4kmmdrtmbkl
ine1yx88l528b
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.query' doesn't exist
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table query drop foreign key FK_kbvi7ufn9v0
60owlt5hfoliu6
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.query' doesn't exist
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table query_data_criteria drop foreign key
FK_nn5ecv2ljvvixddjfpj6wq2xk
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.query_data_criteria' doesn't exist
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table query_data_get drop foreign key FK_17
ved4ttowskvdplsxkaqavgr
| Error 2018-03-13 11:12:42,200 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.query_data_get' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table query_share drop foreign key FK_tkgj8
kdymggd5sg592jfb92gj
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.query_share' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table query_share drop foreign key FK_pcavo
xmpm03kh9lnx208ce2hc
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.query_share' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table string_index drop foreign key FK_7oes
4hqpbiysnkfyxeqk3lw6p
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.string_index' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table user_role drop foreign key FK_apcc8lx
k2xnug8377fatvbn04
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.user_role' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table user_role drop foreign key FK_it77eq9
64jhfqtu54081ebtio
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.user_role' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table user_role drop foreign key FK_998a3yu
e1lj8haalbtcvtslux
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.user_role' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table version drop foreign key FK_q3m84ka7r
lrj0vf4t1ru2bcvh
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.version' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - HHH000389: Unsuccessful: alter table version drop foreign key FK_p1nho9icm
idq1ik80spha2s5w
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExpo
rt  - Table 'ehrserver.version' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table version drop foreign key FK_qku5pv15a
yvcge2p64ko7cvb4
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.version' doesn't exist
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: alter table versioned_composition drop foreign ke
y FK_kkyigtfbihs8x2lafmxhicfcg
| Error 2018-03-13 11:12:42,216 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Table 'ehrserver.versioned_composition' doesn't exist
| Error 2018-03-13 11:12:43,716 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: create index arch_id_path_idx on data_value_index
 (archetype_id, archetype_path)
| Error 2018-03-13 11:12:43,716 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Specified key was too long; max key length is 3072 bytes
| Error 2018-03-13 11:12:43,716 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - HHH000389: Unsuccessful: create index arch_path_idx on data_value_index (archetype_path)
| Error 2018-03-13 11:12:43,732 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Specified key was too long; max key length is 3072 bytes
| Error 2018-03-13 11:12:51,638 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Spring security stateless secretKey not configured or empty. Please, set 'grails.plugin.security.stateless.secretKey' value in your Config.groovy
Message: Spring security stateles secretKey not configured or empty. Please, set 'grails.plugin.security.stateless.secretKey' value in your Config.groovy
    Line | Method
->>  131 | doCall    in SecurityStatelessGrailsPlugin$_closure2

|    266 | run       in java.util.concurrent.FutureTask
|   1149 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    624 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run . . . in java.lang.Thread

C:\ehrserver\ehrserver>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
It also showing below message to set secretKey in config.groovy file.

"Error initializing the application: Spring security stateless secretKey not configured or empty. Please, set 'grails.plugin.security.stateless.secretKey' value in your Config.groovy"

Please suggest.

**Comment by ppazos** [comment]
@saurabhrasp the database logs are a known bug, has no functional effects.

The REST secret key env var should be set, please check the guide.

**Comment by saurabhrasp** [comment]
Pablo,
i already check by creating the system environment variable named "EHRSERVER_REST_SECRET" and some value.
But again same error when trying above command.

**Comment by ppazos** [comment]
@saurabhrasp print the env to see the new value was loaded by the console. After an env var is defined, the console should be closed and opened again. This is the way env vars work on any OS. Please double check.

**Comment by saurabhrasp** [comment]
Pablo,
Cabolabs ehrserver installed and responding locally, i logged in using admin account and created one organisation.
Now we have facing issue like, if we stop cabolabs ehrserver and start again then that created organisation is removed now under organisation link.
Please suggest.

**Comment by ppazos** [comment]
@saurabhrasp you are running grails in dev mode. It creates and destroys the db each time it runs. Run as prod.

**Comment by saurabhrasp** [comment]
Pablo,
one question, can we use prod installation in localhost without https or not?

**Comment by saurabhrasp** [comment]
Pablo,
we have installed the release version of cabolabs ehrserver but then also its development installation is running by default.
Is there any setting so that Production environment will be installed on machine?

**Comment by ppazos** [comment]
@saurabhrasp just pass the environment name to the run-app command: grails prod run-app 

ref: https://grails.github.io/grails2-doc/2.5.6/ref/Command%20Line/run-app.html

There is no different production environment than development, is just an option for Grails on how to run the app with the embedded server. To run it on a server you need to generate the WAR https://grails.github.io/grails2-doc/2.5.6/ref/Command%20Line/war.html
