### ISSUE TITLE
‘/app/docker-entrypoint.sh’: No such file or directory

### ISSUE THREAD

**Issue by romulobusatto** [ppazos/cabolabs-ehrserver#933]
Error when I execute the command:
`docker build -t ehrserver .`

Has anyone ever had it?

`Step 13/15 : RUN chmod +x /app/docker-entrypoint.sh`
`---> Running in d417539edae5`
`chmod: cannot access ‘/app/docker-entrypoint.sh’: No such file or directory`
`The command '/bin/sh -c chmod +x /app/docker-entrypoint.sh' returned a non-zero code: 1`

**Comment by ppazos** [comment]
@romulobusatto did you find a solution? We are not currently using docker, the docker files were provided by a user in the community, you can check the history of them to see who, maybe he can answer your questions. Thanks!

**Comment by robdyke** [comment]
@ppazos @romulobusatto 
I got the cabolabs-ehrserver running in Docker recently. I am in the process of updating the Dockerfile and Docker.md information and adding docker-compose.yml and will submit a PR.

![selection_005](https://user-images.githubusercontent.com/941696/49522618-fba23400-f89f-11e8-9f7e-71b3e320c7e5.png)
